### PR TITLE
Update autographs.md

### PR DESCRIPTION
**Pull request by MatthewCaseres**

### CODE REVIEW

**Review by kennethshsu — APPROVED** [review]

**Comment by kennethshsu** [comment]
@MatthewCaseres please request one more reviewer.

**Comment by MatthewCaseres** [comment]
@kennethshsu you need elevated permissions to request an additional reviewer: https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/managing-repository-roles/repository-roles-for-an-organization

May be easier to trust the people with elevated permissions to manage this individually?

**Comment by kennethshsu** [comment]
Hmm, I see, I don't have the permission to change casact's organization to give everyone in the public Write access, and I think that's even dangerous. But I think that's what is required for anyone to request reviewer(s) for a pull request.

My understanding is that, only members that are added to the repo, can manage and assign reviewers for pull requests.

Ideally, I was hoping that anyone in the world, can submit a pull request, and request reviewers that are already approved by the repo. But that's not the case now... By the way, I am not going to add you to the repo, so we can test out this workflow...

How do you think is the best way to manage this?

**Comment by MatthewCaseres** [comment]
Branch protections like this are useful in putting some red tape around deploying code to a production environment, but since there are low stakes here I was thinking not having the branch protections at all, because only people with permissions can merge it.

**Comment by kennethshsu** [comment]
@jbogaardt how did you set up the chainladder repo protection rules so that review is required for all PR?

I think we want to make sure that changes from all pull requests are reviewed and approved by someone else. This is just good practice and we should encourage such behavior even for newbies.

**Comment by jbogaardt** [comment]
> @jbogaardt how did you set up the chainladder repo protection rules so that review is required for all PR?
> 
> I think we want to make sure that changes from all pull requests are reviewed and approved by someone else. This is just good practice and we should encourage such behavior even for newbies.

I did it through the settings > branches > rules. https://docs.github.com/en/enterprise-server@3.9/repositories/configuring-branches-and-merges-in-your-repository/managing-protected-branches/managing-a-branch-protection-rule

**Review by kennethshsu — APPROVED** [review]

**Comment by kennethshsu** [comment]
@MatthewCaseres I just added you as a maintainer, can you see if you can approve this PR, since I made some changes and had the last commit I cannot be the approver?

**Comment by MatthewCaseres** [comment]
"new changes require approval from someone other than kennethhsu because they were the last pusher." I doubt I can approve my own PR so a third party must step in?

Screenshot 2024-05-28 at 7 03 46 PM

**Review by kennethshsu — APPROVED** [review]

**Comment by kennethshsu** [comment]
Can you try to join the repo as an admin, which I sent an invitation a few days ago? Once you are an admin, you should be able to approve "my" pull request.

Sorry, I am learning how branch protection works on GitHub.

**Comment by MatthewCaseres** [comment]
I seem to have some elevated permissions after receiving the invite but am still unable to merge

**Comment by kennethshsu** [comment]
I think it might be because we both committed to this PR. @jbogaardt can you try to approve this? We only need one approver now.

**Comment by jbogaardt** [comment]
> I think it might be because we both committed to this PR. @jbogaardt can you try to approve this? We only need one approver now.

i can only re-request a review, i dont think im listed as a reviewer.

**Review by jbogaardt — APPROVED** [review]

**Pull request merged**
